### ISSUE TITLE
你好 请问  collection().get() 的分页怎么控制

### ISSUE THREAD

**Issue by HUANGJI97** [orz365/mp-cloud-http#1]

**Comment by orz365** [comment]
和在小程序端的语法一样，使用skip和limit就可以了。
let hcloud = new HttpMpCloud({
    env: env,
    appid,
    appsecret,
    debug: true
})

// 查询记录
hcloud.collection('tb_post').where({
    type:'diqiu'
}).field({
    _id:true
}).skip(2).limit(2).get().then(res => {
    console.log(res.data)
})
